# Site settings
title: Tyler Geneva's portfolio
email: ctg55@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Tyler Geneva's full-stack portfolio site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ctylerg.github.io" # the base hostname & protocol for your site
twitter_username: youontwitter, but I'm not really on twitter
github_username:  ctylerg

# Build settings
markdown: kramdown
